# runner-ci-autoproj provides commands useful to build in CI environments
# run ci clean cache

name: autoproj-runner-humble

on: [pull_request, workflow_dispatch]

jobs:
  setup:
    runs-on: [self-hosted, autoproj-host, linux, x64, default]
    strategy:
      matrix:
        ubuntu: [jammy]
        distro: [humble]
        gazebodistro: [fortress]
      fail-fast: false

    name: "run ros ${{ matrix.distro }} on autoproj"
    steps:
      - name: setup autoprojaction
        uses: actions/checkout@v4
        with:
          repository: Brazilian-Institute-of-Robotics/autoproj_action_runner
          token: ${{ secrets.PAT_ACTION_USER_CIBOT }}
          ref: feat-autoproj-action-runner
      - uses: ./
        with:
          packages: |
            ${{ github.event.repository.name }}
          distro: ${{ matrix.ubuntu }}
          ros-distro: ${{ matrix.distro }}
          gz-distro:  ${{ matrix.gazebodistro }}
          project: "bir.rbim-buildconf"
          build-conf-url: git@github.com:Brazilian-Institute-of-Robotics/bir.rbim-buildconf.git
          build-conf-branch: master
          seed-config: |
            ---
            CODE_ADD_CONFIG: false
            CODE_INTEGRATION: false
            CODE_INSTALL_EXTENSION: false
            CODE_MANAGE_FOLDERS: false
            CODE_APPLY_THEME: false
            apt_dpkg_update: true
            osdeps_mode: all
            GITORIOUS: ssh
            GITHUB: ssh
            GITHUB_ROOT: 'git@github.com:'
            GITHUB_PUSH_ROOT: 'git@github.com:'
            GITHUB_PRIVATE_ROOT: 'git@github.com:'
            USE_PYTHON: true
            python_executable: "/usr/bin/python3"
            ros_version: 2
            ros_distro: '${{ matrix.distro }}'
            gz_distro: '${{ matrix.gazebodistro }}'
            user_shells:
            - bash
          pull_request_body: ${{ github.event.pull_request.body }}
